version: "3.8"
services:
  marvel-api:
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/marvel-api
    command: npm start
    working_dir: /usr/src/marvel-api
    ports:
      - "5000:5000"
    environment:
      MARVEL_PUBLIC_KEY: 2688f5e178b1c2781faa3c31bc1fbed9
      MARVEL_PRIVATE_KEY: 59298ac0c1fbdb9f31847e189611b6325b3db5d4
